services:
 db:
  image: postgres:13
  restart: always
  environment:
   POSTGRES_DB: yourdbname
   POSTGRES_USER: yourusername
   POSTGRES_PASSWORD: yourpassword
  ports:
   - '5432:5432'
  volumes:
   - postgres_data:/var/lib/postgresql/data

 pgadmin:
  image: dpage/pgadmin4
  restart: always
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@example.com
   PGADMIN_DEFAULT_PASSWORD: adminpassword
  ports:
   - '5050:80'
  depends_on:
   - db

volumes:
 postgres_data:
